stages:
  - build-base
  - build-lofarbeam
  - build-dependency
  - test-dependency
  - deploy

build-base:
  variables:
    GIT_STRATEGY: none
    CI_DEBUG_TRACE: "true"
  stage: build-base
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - >
      docker build
      --build-arg CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:base
      -f test/Dockerfile-base .
    - docker push $CI_REGISTRY_IMAGE:base

build-lofarbeam:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: build-lofarbeam
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - >
      docker build
      --build-arg CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE
      --build-arg CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      -f test/Dockerfile-lofarbeam .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

build-dp3:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: build-dependency
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - >
      docker build
      --build-arg CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE
      --tag $CI_REGISTRY_IMAGE/dp3:$CI_COMMIT_SHORT_SHA
      -f test/Dockerfile-dp3 .
    - docker push $CI_REGISTRY_IMAGE/dp3:$CI_COMMIT_SHORT_SHA

build-wsclean:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: build-dependency
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - >
      docker build
      --build-arg CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE
      --tag $CI_REGISTRY_IMAGE/wsclean:$CI_COMMIT_SHORT_SHA
      -f test/Dockerfile-wsclean .
    - docker push $CI_REGISTRY_IMAGE/wsclean:$CI_COMMIT_SHORT_SHA

test-dp3:
  variables:
    GIT_STRATEGY: none
  stage: test-dependency
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - >
      docker run
      $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      /opt/lofarbeam/lofarbeam/test/run-test.sh

test-wsclean:
  variables:
    GIT_STRATEGY: none
  stage: test-dependency
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - >
      docker run
      $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      /opt/lofarbeam/lofarbeam/test/run-test.sh

deploy:
  variables:
    GIT_STRATEGY: none
  only:
    - master
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
