# Copyright (C) 2020 ASTRON (Netherlands Institute for Radio Astronomy)
# SPDX-License-Identifier: GPL-3.0-or-later

workflow:
  rules:
    # don't create a pipeline if its a commit pipeline, on a branch and that branch has open merge requests (bc we will get a MR build instead)
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - when: always

stages:
  - prepare
  - build
  - package
  - oskar-comparison
  - deploy

build-base:
  stage: prepare
  script:
    - docker build --tag everybeam_base:${CI_COMMIT_SHORT_SHA} -f ./docker/Dockerfile-base .

clang-format:
  stage: build
  needs: ["build-base"]
  image: everybeam_base:${CI_COMMIT_SHORT_SHA}
  script:
    - ./scripts/run-clang-format.sh
  rules:
    # Do not add for schedules
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - when: on_success

# Build a debug version of EveryBeam from the base image
test-and-coverage:
  stage: build
  needs: ["build-base"]
  image: everybeam_base:${CI_COMMIT_SHORT_SHA}
  script:
    - WORKDIR=$PWD
    # Download casacore wsrt measures
    - wget -q ftp://ftp.astron.nl/outgoing/Measures/WSRT_Measures.ztar && tar -xf WSRT_Measures.ztar -C /var/lib/casacore/data/ && rm -f WSRT_Measures.ztar
    # Build in Debug mode
    - mkdir build && cd build
    - cmake -DCMAKE_INSTALL_PREFIX=.. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DBUILD_WITH_PYTHON=ON -DCMAKE_CXX_FLAGS="-coverage" -DCMAKE_EXE_LINKER_FLAGS="-coverage" ..
    - make install -j8
    - ctest -j4 -T test
    # Capture coverage
    - gcovr -r .. -e '.*/external/.*' -e '.*/CompilerIdCXX/.*' -e '.*/test/.*' -e '.*/demo/.*' --json -o run-unit.json
    - gcovr --add-tracefile run-unit.json --xml > coverage.xml
    - gcovr --add-tracefile run-unit.json
    # Check whether pyeverybeam modules can be found from home directory after setting the PYTHONPATH
    - PYVERSION=`python3 --version | grep -P -o ".*\s\K\d\.\d(?=\.\d)"`
    - export PYTHONPATH=${WORKDIR}/lib/python${PYVERSION}/dist-packages
    - cd && python3 -c "import everybeam"
  artifacts:
    reports:
      # NOTE: artifacts only work with relative paths...
      cobertura: build/coverage.xml
      junit: build/cpp/test/unittests.xml

build-everybeam:
  stage: build
  needs: ["build-base"]
  script:
    - docker build --build-arg BASE_TAG=${CI_COMMIT_SHORT_SHA} --tag everybeam:${CI_COMMIT_SHORT_SHA} -f ./docker/Dockerfile-everybeam .

build-doc:
  stage: build
  needs: ["build-base"]
  image: everybeam_base:${CI_COMMIT_SHORT_SHA}
  script:
    - EVERYBEAM_PATH=$PWD
    - mkdir build && cd build
    - cmake $EVERYBEAM_PATH
    - make doc
  artifacts: # Only for master the docs are published; for branches it may be useful to browse the artifacts
    paths:
    - build/doc/html
  rules:
    # Only add job for commits to master or on merge_request_event
    # NOTE: creates duplicate pipelines in case of open MR,
    # see https://gitlab.com/gitlab-org/gitlab/-/issues/201845
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

build-package:
  stage: package
  needs: ["build-everybeam"]
  image: everybeam:${CI_COMMIT_SHORT_SHA}
  script:
    - mkdir everybeam_package
    - export SRC=$(pwd)
    - cd /opt/everybeam/build
    - make package
    - mv $(ls -1 *.deb) $SRC/everybeam_package/
  artifacts:
    paths:
    - everybeam_package/
  rules:
    # The package is built only during a merge_request_event, a merge to master,
    # or when the pipeline is triggered by a tag event.
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_TAG'
    - if: '$UPLOAD_PACKAGE'

build-compare-oskar:
  stage: oskar-comparison
  image: everybeam:${CI_COMMIT_SHORT_SHA}
  needs: ["build-everybeam"]
  before_script:
    - mkdir -p /opt/oskar/build
    - cd /opt/oskar && git clone https://github.com/OxfordSKA/OSKAR.git
    # Check-out at specific version, before HDF5 got broken
    - cd OSKAR && git checkout bb3f9112e20e1d5e9b91b695828f993ad6bc91ee
    - cd /opt/oskar/build
  script:
    # OSKAR cpp install
    - cmake -DCMAKE_INSTALL_PREFIX=.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXE_LINKER_FLAGS="-coverage" ../OSKAR/
    - make -j8
    - make install
    # Python install
    - export OSKAR_INC_DIR=/opt/oskar/include && export OSKAR_LIB_DIR=/opt/oskar/lib
    - cd ./../OSKAR/python && python3 setup.py install
    - export PATH=/opt/oskar/bin:$PATH
    # Run OSKAR comparison, set some env variables for this session
    - export NPIXELS=8 && export APPLY_TRANSPOSE=OFF && MAX_ORDER=3 && TOLERANCE=1e-12
    - cd /opt/everybeam/build
    - make VERBOSE=1 comparison-oskar-basefunctions
    # Run OSKAR stationresponse comparison
    - export NPIXELS=32 TOLERANCE=1e-5
    - make VERBOSE=1 comparison-oskar-station-response
  rules:
    # Only add job for schedules, on merge_request_event, and on master
    # NOTE: creates duplicate pipelines in case of open MR,
    # see https://gitlab.com/gitlab-org/gitlab/-/issues/201845
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "master"'

deploy-doc:
  stage: deploy
  needs: ["build-doc"]
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | base64 -d | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H dop810 > ~/.ssh/known_hosts
  script:
    - scp -r build/doc/html/* citt@dop810:EveryBeam
  rules:
    # Only add job when ran on master and not a scheduled job, i.e. when merging
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule"'

deploy-image:
  variables:
    GIT_STRATEGY: none
  needs: ["build-everybeam"]
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag everybeam:${CI_COMMIT_SHORT_SHA} $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  rules:
    # Only add job when ran on master and not a scheduled job, i.e. when merging
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule"'

deploy-package:
  stage: deploy
  needs: ["build-package"]
  image: everybeam:${CI_COMMIT_SHORT_SHA}
  script:
    - pip3 install aptly-api-client
    - chmod -R 700 external/schaap-packaging
    - cd everybeam_package
    - export FILES=$(ls -1 $PWD/*.deb)
    - echo UPLOADING files $FILES
    # The following example command must be executed first or else the update will fail because there is no repository
    # create_repo.py -a amd64 -c testing -d bionic --gpg-key ${GPG_KEY} --gpg-passphrase ${GPG_PASS} schaap
    - ../external/schaap-packaging/update_repo.py --cleanup -d bionic --gpg-key ${GPG_KEY} --gpg-passphrase ${GPG_PASS} schaap ${FILES}
  rules:
    # Only run on master because GPG_KEY and GPG_PASS are protected and therefore only available on protected branches.
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: never
    - if: '$UPLOAD_PACKAGE'


check-stack:
  variables:
    # Pass commit hash to downstream pipeline
    EVERYBEAM_TRIGGER_HASH: $CI_COMMIT_SHA
  stage: deploy
  needs: []
  trigger:
    project: RD/schaap-stack
    branch: master
    # This will mirror the status of the downstream pipeline
    strategy: depend
  rules:
    # Only add job during merge request event
    # NOTE: creates duplicate pipelines in case of open MR,
    # see https://gitlab.com/gitlab-org/gitlab/-/issues/201845
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
