main:
    script:
    - docker build --build-arg CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA -t my-image:$CI_COMMIT_SHORT_SHA test
    - docker run my-image:$CI_COMMIT_SHORT_SHA /opt/lofarbeam/lofarbeam/test/run_test.sh
