# Copyright (C) 2021 ASTRON (Netherlands Institute for Radio Astronomy)
# SPDX-License-Identifier: GPL-3.0-or-later

# This file contains the pipelines that run on the SKAO repository of IDG, which
# is at https://gitlab.com/ska-telescope/sdp/ska-sdp-func-everybeam

include:
  - local: .gitlab-ci.common.yml
# Create Gitlab CI badges from CI metrics
# https://developer.skao.int/en/latest/tools/continuousintegration.html#automated-collection-of-ci-health-metrics-as-part-of-the-ci-pipeline
  - project: ska-telescope/templates-repository
    file: gitlab-ci/includes/post_step.yml

# Caching 'public' allows keeping the 'pages' output of multiple branches / MRs.
cache:
  paths:
    - public

pages:
  stage: deploy
  needs: ["versioning","test-and-coverage"]
  image: $BASE_IMAGE
  script:
    - echo Deploying GitLab pages to $CI_PAGES_URL/$CI_COMMIT_REF_SLUG
    - mkdir -p public/$CI_COMMIT_REF_SLUG
    - cd public/$CI_COMMIT_REF_SLUG
    - gcovr -j$(($(nproc)/2 > 0 ? $(nproc)/2:1)) -r ../../ -a ../../build/run-unit.json --html-details index.html
  artifacts:
    name: $CI_COMMIT_REF_SLUG
    paths:
      - public
    expire_in: 1 week
