# Copyright (C) 2022 ASTRON (Netherlands Institute for Radio Astronomy)
# SPDX-License-Identifier: GPL-3.0-or-later

# base
FROM ubuntu:22.04
RUN export DEBIAN_FRONTEND="noninteractive" && apt-get update && apt-get upgrade -y && \
# install astronomy packages
    apt-get -y install casacore-dev \
        libcfitsio-dev wcslib-dev python3-pip
# install misc packages
RUN apt-get update && \
    apt-get -y install wget git make cmake g++ doxygen graphviz ninja-build \
# install dependencies
        libboost-all-dev libhdf5-dev libfftw3-dev \
        libblas-dev liblapack-dev libgsl-dev libxml2-dev \
        libpng-dev libgtkmm-3.0-dev libpython3.9-dev && \
# Install python dependencies
    pip3 install gcovr pytest pytest-lazy-fixture \
    # Install python requirements for the OSKAR "integration" test
        numpy scipy h5py astropy tqdm matplotlib pandas lofarantpos \
    # Install python requirements for building documentation
        sphinx sphinx_rtd_theme breathe myst-parser \
    # Install python requirements for packaging
        aptly-api-client