# Copyright (C) 2021 ASTRON (Netherlands Institute for Radio Astronomy)
# SPDX-License-Identifier: GPL-3.0-or-later

# This is a Dockerfile specifically to test compilation using
# gcc 11, which is as of writing (Aug 2021) not standard yet, but is more
# strict than gcc 10.

FROM ubuntu:18.04

RUN export DEBIAN_FRONTEND=noninteractive && apt-get update && \
    apt-get install -y \
    build-essential \
    casacore-data casacore-dev \
    cmake \
    libblas-dev liblapack-dev \
    libpython3-dev \
    libboost-filesystem-dev \
    libboost-system-dev \
    libboost-test-dev \
    libcfitsio-dev \
    libfftw3-dev \
    libgsl-dev \
    libhdf5-serial-dev \
    pkg-config \
    python3 \
    python3-distutils \
    wget \
    software-properties-common && \
  echo -ne "\n \n"| add-apt-repository ppa:ubuntu-toolchain-r/test && \
  apt-get update -qq && \
  apt-get install -y gcc-11 g++-11 gfortran-11

ADD . /src
WORKDIR /src

RUN \
  mkdir /build && \
  cd /build && \
  CC=/usr/bin/gcc-11 CXX=/usr/bin/g++-11 cmake -DBUILD_LOBES=ON ../src && \
  make -j`nproc` && \
  make install
