ARG BASE_TAG=latest
FROM everybeam_base:$BASE_TAG

ENV EVERYBEAMDIR /opt/everybeam
ADD . ${EVERYBEAMDIR}/EveryBeam

RUN mkdir -p ${EVERYBEAMDIR}/build && cd ${EVERYBEAMDIR}/build \
    && cmake -DBUILD_WITH_PYTHON=ON -DCMAKE_INSTALL_PREFIX=.. ../EveryBeam \
    && make -j8 && make install -j8
