# Copyright (C) 2020 ASTRON (Netherlands Institute for Radio Astronomy)
# SPDX-License-Identifier: GPL-3.0-or-later

# Dockerfile for the code formatting tools.
# Use Ubuntu 20.04, since clang-format-12 is not available in Ubuntu 18.04.

FROM ubuntu:20.04
RUN export DEBIAN_FRONTEND="noninteractive" && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get -y install git python3-pip clang-format-12 && \
    ln -sf clang-format-12 /usr/bin/clang-format && \
    pip3 install cmake-format
